name: Deploy Agent Vee 007 to Firebase

on:
  push:
    branches:
      - main   # change branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout repo
    - name: Checkout
      uses: actions/checkout@v4

    # Authenticate to Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    # Install Firebase CLI
    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    # Build the Next.js client
    - name: Install client dependencies
      run: |
        cd client
        npm install
        npm run build

    # Deploy to Firebase Hosting
    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting --project ${{ secrets.GCP_PROJECT_ID }}
